# Generated by Django 4.0 on 2021-12-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название отдела')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='ProgramingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия сотрудника')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст сотрудника')),
                ('gender', models.CharField(blank=True, choices=[('M', 'F')], max_length=1, verbose_name='Пол')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.departament', verbose_name='Департамент')),
                ('programing_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.programinglanguage', verbose_name='Язык программирования сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
